; jepFixes: Multiple Sitreps REDUX MCM defaults. Idi 2026-09-15: change costs 10 intel (a decision), remove and seal stay 0 (unused: no empty missions wanted, block list replaces sealing).

[MultipleSitreps_REDUX.MultipleSitreps_REDUX_MCM_Defaults]
GuaranteedSitRepAmount=1
RandomAdditionalSitRepAmount=1
RandomAdditionalSitRepChance=50
ChangeSitRepIntelCost=10
RemoveSitRepIntelCost=0
SealSitRepIntelCost=0
